[project]
name = "ipclick"
version = "0.1.0"
description = "强大下载器"
authors = [
    {name = "'元气码农少女酱'",email = "'1276162429@qq.com'"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
